import { useState } from "react";
import CloseApproachChart from "../components/CloseApproachChart";
import {
  AVOIDANCE_CHART_URL,
  CLOSE_APPROACH_WINDOW_MIN,
} from "../lib/api";
import { useTrajectories } from "../hooks/useTrajectories";
import { useCloseApproachGeometry } from "../lib/closeApproach";
import {
  formatDeltaV,
  formatKm,
  formatUtcLong,
  formatVelocity,
} from "../lib/format";
import { useWorkspace } from "../lib/workspace";
import "./VisualizationPage.css";

function KpiCard({ label, value, unit, caption, tone }) {
  return (
    <article className={`viz-kpi ${tone ? `tone-${tone}` : ""}`}>
      <span className="viz-kpi-label">{label}</span>
      <strong className="viz-kpi-value mono">
        {value}
        {unit && <small> {unit}</small>}
      </strong>
      <span className="viz-kpi-caption">{caption}</span>
    </article>
  );
}

function FullOrbitView() {
  return (
    <figure className="full-orbit">
      <div className="ca-chart-head">
        <div>
          <h4 className="ca-chart-title">Full Orbit View</h4>
          <p className="ca-chart-sub mono">
            Backend-generated 24 h conjunction and avoidance plot
          </p>
        </div>
        <span className="ca-projection mono">SGP4 · TCA ± 12 h window</span>
      </div>
      <div className="full-orbit-frame">
        <img
          src={AVOIDANCE_CHART_URL}
          alt="Backend-generated 24-hour conjunction and avoidance trajectory chart"
          loading="lazy"
        />
      </div>
      <figcaption className="ca-legend">
        <span className="ca-legend-item">
          Generated by the backend from the simulated avoidance scenario;
          it is not regenerated per catalog selection.
        </span>
      </figcaption>
    </figure>
  );
}

const READING_GUIDE = [
  { marker: "line", markerClass: "original", text: "Original satellite trajectory" },
  { marker: "line", markerClass: "post", text: "Post-maneuver trajectory" },
  { marker: "line", markerClass: "debris", text: "Debris trajectory" },
  { marker: "x", markerClass: "", text: "Closest approach / TCA" },
  { marker: "dot", markerClass: "", text: "Maneuver point" },
];

/**
 * Orbital trajectory visualization. The close-approach view is drawn from
 * the backend's own SGP4 ephemeris export; every number shown comes from
 * the existing API payloads.
 */
export default function VisualizationPage() {
  const { avoidance, avoidanceEvent } = useWorkspace();
  const {
    status: ephemerisStatus,
    trajectories,
    retry: retryEphemeris,
  } = useTrajectories();
  const [tab, setTab] = useState("close");

  const geometry = useCloseApproachGeometry({
    trajectories,
    satelliteNorad: avoidanceEvent?.satellite_norad,
    debrisNorad: avoidanceEvent?.debris_norad,
    tca: avoidanceEvent?.time,
    maneuverTime: avoidance?.maneuver_time,
  });

  if (!avoidance) {
    return (
      <main className="page">
        <div className="ops-section-head">
          <div>
            <p className="ops-eyebrow">Trajectory analysis</p>
            <h2>Orbital Trajectory Visualization</h2>
          </div>
        </div>
        <div className="panel notfound-panel">
          <p>
            No avoidance scenario is available in the current backend
            dataset, so there is no maneuver to visualize.
          </p>
        </div>
      </main>
    );
  }

  const event = avoidanceEvent;
  const improvement = Number(avoidance.miss_distance_improvement_km);

  return (
    <main className="page">
      {/* Page header + view tabs */}
      <div className="ops-section-head">
        <div>
          <p className="ops-eyebrow">Trajectory analysis</p>
          <h2>Orbital Trajectory Visualization</h2>
          <p className="ops-lede viz-lede">
            Close approach view around TCA with and without avoidance maneuver
          </p>
        </div>
        <div className="viz-tabs" role="tablist" aria-label="Visualization view">
          <button
            type="button"
            role="tab"
            aria-selected={tab === "close"}
            className={`viz-tab ${tab === "close" ? "active" : ""}`}
            onClick={() => setTab("close")}
          >
            Close Approach
          </button>
          <button
            type="button"
            role="tab"
            aria-selected={tab === "full"}
            className={`viz-tab ${tab === "full" ? "active" : ""}`}
            onClick={() => setTab("full")}
          >
            Full Orbit
          </button>
        </div>
      </div>

      {/* KPI row — all values from the avoidance API payload */}
      <div className="viz-kpis">
        <KpiCard
          label="Before maneuver"
          value={formatKm(avoidance.original_miss_distance_km)}
          unit="km"
          caption="Closest approach distance"
        />
        <KpiCard
          label="After maneuver"
          value={formatKm(avoidance.new_miss_distance_km)}
          unit="km"
          caption="Closest approach distance"
        />
        <KpiCard
          label="Improvement"
          value={`+${formatKm(improvement)}`}
          unit="km"
          caption="Increase in separation"
          tone="ok"
        />
        <KpiCard
          label="TCA"
          value={event ? formatUtcLong(event.time) : "—"}
          caption="Time of closest approach"
        />
      </div>

      {/* Chart + event panel */}
      <div className="viz-main">
        <div className="viz-chart-col">
          {tab === "close" ? (
            ephemerisStatus === "loading" || ephemerisStatus === "idle" ? (
              <div className="viz-status">
                <span className="mono">Loading SGP4 ephemeris…</span>
              </div>
            ) : ephemerisStatus === "error" ? (
              <div className="viz-status warn">
                <span className="mono">
                  Ephemeris export unavailable — the backend trajectory
                  dataset could not be loaded. Use the Full Orbit view.
                </span>
              </div>
            ) : geometry ? (
              <CloseApproachChart
                geometry={geometry}
                avoidance={avoidance}
              />
            ) : (
              <div className="viz-status">
                <span className="mono">
                  The ±{CLOSE_APPROACH_WINDOW_MIN} min window around this
                  event's TCA is not fully covered by the loaded ephemeris —
                  it may be stale after a backend re-run.
                </span>
                <button
                  type="button"
                  className="viz-retry mono"
                  onClick={retryEphemeris}
                >
                  Reload trajectory data
                </button>
              </div>
            )
          ) : (
            <FullOrbitView />
          )}

          {/* How to read this plot */}
          <section className="viz-guide">
            <h4>How to Read This Plot</h4>
            <ol>
              {READING_GUIDE.map((item, index) => (
                <li key={item.text}>
                  <span className="guide-num mono">{index + 1}</span>
                  <span className={`guide-marker ${item.marker}`} aria-hidden="true">
                    {item.marker === "line" && (
                      <span className={`legend-line ${item.markerClass}`} />
                    )}
                    {item.marker === "x" && "✕"}
                    {item.marker === "dot" && <span className="legend-dot" />}
                  </span>
                  <span className="guide-text">{item.text}</span>
                </li>
              ))}
            </ol>
          </section>
        </div>

        {/* Selected event panel */}
        <aside className="viz-event-panel">
          <div className="viz-panel-head">
            <span className="metric-label">Selected Event</span>
          </div>

          <div className="viz-event-objects">
            <div className="viz-object">
              <span className="object-role">Spacecraft</span>
              <strong className="object-name">
                {event?.satellite_name ?? avoidance.satellite}
              </strong>
              {event && (
                <span className="object-norad mono">
                  NORAD {event.satellite_norad}
                </span>
              )}
            </div>

            <span className="viz-object-sep" aria-hidden="true">
              <span className="sep-line" />
              <span className="sep-arrows">↕</span>
              <span className="sep-line" />
            </span>

            <div className="viz-object debris">
              <span className="object-role">Debris</span>
              <strong className="object-name">
                {event?.debris_name ?? avoidance.debris}
              </strong>
              {event && (
                <span className="object-norad mono">
                  NORAD {event.debris_norad}
                </span>
              )}
            </div>
          </div>

          <div className="viz-event-metrics">
            <span className="metric-label">Key Metrics</span>
            <dl className="viz-metric-rows">
              <div className="viz-metric-row">
                <dt>Miss Distance (Before)</dt>
                <dd className="mono">
                  {formatKm(avoidance.original_miss_distance_km)} km
                </dd>
              </div>
              <div className="viz-metric-row">
                <dt>Miss Distance (After)</dt>
                <dd className="mono">
                  {formatKm(avoidance.new_miss_distance_km)} km
                </dd>
              </div>
              <div className="viz-metric-row">
                <dt>Improvement</dt>
                <dd className="mono ok">
                  +{formatKm(improvement)} km
                </dd>
              </div>
              <div className="viz-metric-row">
                <dt>Relative Velocity</dt>
                <dd className="mono">
                  {event ? `${formatVelocity(event.relative_velocity_km_s)} km/s` : "—"}
                </dd>
              </div>
              <div className="viz-metric-row">
                <dt>TCA</dt>
                <dd className="mono">
                  {event ? formatUtcLong(event.time) : "—"}
                </dd>
              </div>
              <div className="viz-metric-row">
                <dt>Maneuver Δv</dt>
                <dd className="mono">
                  {formatDeltaV(avoidance.delta_v_m_s)} m/s
                </dd>
              </div>
            </dl>
          </div>

          <div className="viz-disclaimer" role="note">
            This is a simulation result for decision support. Not a
            flight-certified command.
          </div>
        </aside>
      </div>
    </main>
  );
}
